### PR TITLE
Added the '--user-agent' argument

### PR DESCRIPTION
**Pull request by FFace32**
Recently I haven't been able to connect because I was getting this error:

acc

Using an user agent with a different OS fixes it.

So, I added the `--user-agent` argument, can be set to anything.

### CODE REVIEW

**Comment by dlenski** [comment]
This is already possible. You just need to run as `gp-saml-gui -- --useragent "whatever"` (see the documentation regarding appending extra arguments for OpenConnect).

I'm trying specifically **not** to add options which simply get passed along to OpenConnect, because this facility already exists.

**Comment by FFace32** [comment]
> This is already possible. You just need to run as `gp-saml-gui -- --useragent "whatever"` (see the documentation regarding appending extra arguments for OpenConnect).
> 
> I'm trying specifically **not** to add options which simply get passed along to OpenConnect, because this facility already exists.

That doesn't fix the issue I'm experiencing, since the *You cannot access this right now* message I'm receiving comes from the interactive login (in this case Microsoft's SSO) which gets it's user agent from the WebKit WebView.

**Comment by dlenski** [comment]
> That doesn't fix the issue I'm experiencing, since the You cannot access this right now message I'm receiving comes from the interactive login (in this case Microsoft's SSO) which gets it's user agent from the WebKit WebView.

Ah, yes, I see. I shouldn't have jumped to conclusions here.

In that case, we should _also_ pass along the value provided to `openconnect --useragent VALUE` (similar to arguments like `--clientos` and `--allow-insecure-crypto`, where we attempt to coordinate/align the HTTP behavior between python-requests, Gtk WebView, and `openconnect`.

Is the User-Agent value you need provide `PAN GlobalProtect`? (https://gitlab.com/openconnect/openconnect/blob/master/auth-globalprotect.c#L41-44) Probably this should just be the default.

**Comment by dlenski** [comment]
@FFace32, could you test https://github.com/dlenski/gp-saml-gui/commits/configurable_AND_consistent_user_agent?

I added a few tweaks in 22c5e131140b7601f1560c509ea2f5daf8ebc1f7, to ensure that the same user-agent string is provided consistently throughout. And also to add `--useragent` as an alternative option name for consistency with OpenConnect.

**Comment by FFace32** [comment]
> @FFace32, could you test https://github.com/dlenski/gp-saml-gui/commits/configurable_AND_consistent_user_agent?
> 
> I added a few tweaks in [22c5e13](https://github.com/dlenski/gp-saml-gui/commit/22c5e131140b7601f1560c509ea2f5daf8ebc1f7), to ensure that the same user-agent string is provided consistently throughout. And also to add `--useragent` as an alternative option name for consistency with OpenConnect.

Yup! It works just fine.

Thank you!

**Comment by dlenski** [comment]
Merged in e73026c85b42cbfed0a7a074e4f4b5c4d471aeb8. Thanks!

**Pull request closed without merging**
